### ISSUE TITLE
Possible issue with 2.0.8 security fix

### ISSUE THREAD

**Issue by jsdalton** [rack/rack#1432]
Just upgrading to 2.0.8 after the fix was released and I'm running into an issue that appears to relate to the introduction of the Session::Id format for session ids. I've only cursorily reviewed the change but from what I can tell, whereas previously the session id was just a simple (cryptographically generated) string, it is now wrapped in the Session::id class.

The problem we ran into comes right about here:
https://github.com/rack/rack/blob/master/lib/rack/utils.rb#L249

The `value` here, at least in our use case, is an instance of Session::Id where before it was just a string. In the line above it is being rendered as a string, where it is running into this:

https://github.com/rack/rack/blob/master/lib/rack/session/abstract/id.rb#L33

This is in the context of a Rails appilcation using the `CacheStore` session backend, and I haven't determined whether and how we might workaround this, but for the time being I thought I'd open the issue, and raise the following questions/concerns:

* Is this an improper use of the session id value? In other words, perhaps somehow we are "doing it wrong" and the error raised is valid indicator of that.
* If not, why is the Session::Id object not allowed to be rendered a a string (i.e. because an error is intentionally raised)?
* If there is a valid explanation for the above, would it not make sense to raise either a more specific error than `RuntimeError`, or an error message giving the reason it's a problem, or ideally both? The bare `RuntimeError` isn't very helpful.

Thanks.

**Comment by jsdalton** [comment]
Looks like there's an update on the Rails side: https://github.com/rails/rails/commit/ad2da1ad82742354a73cf30be658574d9bd567f0 This could possibly address the issue I reported.

**Comment by rafaelfranca** [comment]
Can you provide an example application that reproduce the issue?

**Comment by danillos** [comment]
After update I had this issue, so I rollback it to 2.0.7 to stop the error.

```
	21: from /usr/share/rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	20: from /usr/share/rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	19: from /usr/share/rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2/lib/action_controller/metal/strong_parameters.rb:8:in `<main>'
	18: from /usr/share/rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	17: from /usr/share/rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	16: from /usr/share/rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	15: from /usr/share/rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	14: from /usr/share/rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	13: from /usr/share/rvm/gems/ruby-2.6.5/gems/rack-test-1.1.0/lib/rack/test.rb:4:in `<main>'
	12: from /usr/share/rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	11: from /usr/share/rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	10: from /usr/share/rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 9: from /usr/share/rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	 8: from /usr/share/rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	 7: from /usr/share/rvm/gems/ruby-2.6.5/gems/rack-test-1.1.0/lib/rack/test/cookie_jar.rb:4:in `<main>'
	 6: from /usr/share/rvm/gems/ruby-2.6.5/gems/rack-test-1.1.0/lib/rack/test/cookie_jar.rb:5:in `<module:Rack>'
	 5: from /usr/share/rvm/gems/ruby-2.6.5/gems/rack-test-1.1.0/lib/rack/test/cookie_jar.rb:6:in `<module:Test>'
	 4: from /usr/share/rvm/gems/ruby-2.6.5/gems/rack-test-1.1.0/lib/rack/test/cookie_jar.rb:7:in `<class:Cookie>'
	 3: from /usr/share/rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `load_missing_constant'
	 2: from /usr/share/rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `rescue in load_missing_constant'
	 1: from /usr/share/rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
/usr/share/rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `block in load_missing_constant': uninitialized constant Rack::Utils (NameError)
```

**Comment by baelter** [comment]
Also having issues: ```
16:46:50 web.1     | 2019-12-19 16:46:50 - RuntimeError - :
16:46:50 web.1     | 	/Users/anders/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.0.8/lib/rack/session/abstract/id.rb:31:in `to_s'
16:46:50 web.1     | 	/Users/anders/.rbenv/versions/2.6.5/lib/ruby/2.6.0/uri/common.rb:369:in `encode_www_form_component'
16:46:50 web.1     | 	/Users/anders/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.0.8/lib/rack/utils.rb:29:in `escape'
16:46:50 web.1     | 	/Users/anders/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.0.8/lib/rack/utils.rb:266:in `block in add_cookie_to_header'
16:46:50 web.1     | 	/Users/anders/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.0.8/lib/rack/utils.rb:266:in `map'
16:46:50 web.1     | 	/Users/anders/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.0.8/lib/rack/utils.rb:266:in `add_cookie_to_header'
16:46:50 web.1     | 	/Users/anders/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.0.8/lib/rack/response.rb:184:in `set_cookie'```

Calling `set_cookie('key', value: 'val', path: '/path')`

**Comment by jimbali** [comment]
We are also experiencing issues with version 1.16.12, which fixes the same CVE:

```
# /usr/local/bundle/gems/rack-1.6.12/lib/rack/session/abstract/id.rb:34:in `to_s'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rack-1.6.12/lib/rack/utils.rb:36:in `escape'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rack-1.6.12/lib/rack/utils.rb:329:in `block in set_cookie_header!'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rack-1.6.12/lib/rack/utils.rb:329:in `map'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rack-1.6.12/lib/rack/utils.rb:329:in `set_cookie_header!'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/cookies.rb:352:in `block in write'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/cookies.rb:352:in `each'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/cookies.rb:352:in `write'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/cookies.rb:564:in `call'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/query_cache.rb:36:in `call'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/airbrake-4.3.1/lib/airbrake/rails/middleware.rb:13:in `call'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/railties-4.2.11.1/lib/rails/rack/logger.rb:38:in `call_app'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rails_semantic_logger-4.1.3/lib/rails_semantic_logger/extensions/rails/rack/logger.rb:21:in `call'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rack-1.6.12/lib/rack/methodoverride.rb:22:in `call'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rack-1.6.12/lib/rack/runtime.rb:18:in `call'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rack-1.6.12/lib/rack/lock.rb:17:in `call'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/static.rb:120:in `call'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rack-1.6.12/lib/rack/sendfile.rb:113:in `call'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/airbrake-4.3.1/lib/airbrake/user_informer.rb:16:in `_call'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/airbrake-4.3.1/lib/airbrake/user_informer.rb:12:in `call'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/railties-4.2.11.1/lib/rails/engine.rb:518:in `call'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/railties-4.2.11.1/lib/rails/application.rb:165:in `call'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rack-test-0.6.3/lib/rack/test.rb:124:in `request'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/testing/integration.rb:297:in `process'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/testing/integration.rb:32:in `get'
build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/testing/integration.rb:346:in `block (2 levels) in <module:Runner>'
```

**Comment by AnrichVS** [comment]
We're also experiencing this issue on Rack 2.0.8 and Rails 5.2.3. In our case it happens when viewing the [Sidekiq status page](https://github.com/mperham/sidekiq/wiki/Monitoring) (Sidekiq 5.2.7). The following error occurs:

```
NoMethodError (undefined method `match' for #<Rack::Session::SessionId:0x000055e01893c0a8>):
  
redis-store (1.8.1) lib/redis/store/namespace.rb:137:in `interpolate'
redis-store (1.8.1) lib/redis/store/namespace.rb:128:in `namespace'
redis-store (1.8.1) lib/redis/store/namespace.rb:23:in `get'
redis-rack (2.0.6) lib/rack/session/redis.rb:38:in `block (2 levels) in get_session'
connection_pool (2.2.2) lib/connection_pool.rb:65:in `block (2 levels) in with'
```

**Comment by rihardssceredins** [comment]
Like @AnrichVS we're also experiencing issues with Rack 2.0.8 when viewing Sidekiq (5.2.7) on Rails 5.1.7 but with a different error:

```
F, [2019-12-24T10:20:05.975216 #14557] FATAL -- :
F, [2019-12-24T10:20:05.975313 #14557] FATAL -- : RuntimeError ():
F, [2019-12-24T10:20:05.977613 #14557] FATAL -- :
F, [2019-12-24T10:20:05.978807 #14557] FATAL -- : rack (2.0.8) lib/rack/session/abstract/id.rb:31:in `to_s'
redis (4.1.3) lib/redis/connection/command_helper.rb:18:in `block in build_command'
redis (4.1.3) lib/redis/connection/command_helper.rb:10:in `each'
redis (4.1.3) lib/redis/connection/command_helper.rb:10:in `build_command'
redis (4.1.3) lib/redis/connection/ruby.rb:391:in `write'
redis (4.1.3) lib/redis/client.rb:281:in `block in write'
redis (4.1.3) lib/redis/client.rb:260:in `io'
redis (4.1.3) lib/redis/client.rb:279:in `write'
redis (4.1.3) lib/redis/client.rb:238:in `block (3 levels) in process'
redis (4.1.3) lib/redis/client.rb:232:in `each'
redis (4.1.3) lib/redis/client.rb:232:in `block (2 levels) in process'
redis (4.1.3) lib/redis/client.rb:384:in `ensure_connected'
redis (4.1.3) lib/redis/client.rb:231:in `block in process'
redis (4.1.3) lib/redis/client.rb:319:in `logging'
redis (4.1.3) lib/redis/client.rb:230:in `process'
redis (4.1.3) lib/redis/client.rb:125:in `call'
redis (4.1.3) lib/redis.rb:914:in `block in get'
redis (4.1.3) lib/redis.rb:52:in `block in synchronize'
/home/deployer/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
redis (4.1.3) lib/redis.rb:52:in `synchronize'
redis (4.1.3) lib/redis.rb:913:in `get'
redis-store (1.6.0) lib/redis/store/interface.rb:5:in `get'
redis-store (1.6.0) lib/redis/store/serialization.rb:17:in `get'
redis-store (1.6.0) lib/redis/store/namespace.rb:23:in `block in get'
redis-store (1.6.0) lib/redis/store/namespace.rb:89:in `namespace'
redis-store (1.6.0) lib/redis/store/namespace.rb:23:in `get'
redis-rack (2.0.5) lib/rack/session/redis.rb:38:in `block (2 levels) in get_session'
redis-rack (2.0.5) lib/redis/rack/connection.rb:18:in `with'
redis-rack (2.0.5) lib/rack/session/redis.rb:79:in `with'
redis-rack (2.0.5) lib/rack/session/redis.rb:38:in `block in get_session'
redis-rack (2.0.5) lib/rack/session/redis.rb:67:in `with_lock'
redis-rack (2.0.5) lib/rack/session/redis.rb:37:in `get_session'
rack (2.0.8) lib/rack/session/abstract/id.rb:490:in `find_session'
rack (2.0.8) lib/rack/session/abstract/id.rb:307:in `load_session'
actionpack (5.1.7) lib/action_dispatch/middleware/session/abstract_store.rb:44:in `block in load_session'
actionpack (5.1.7) lib/action_dispatch/middleware/session/abstract_store.rb:52:in `stale_session_check!'
actionpack (5.1.7) lib/action_dispatch/middleware/session/abstract_store.rb:44:in `load_session'
actionpack (5.1.7) lib/action_dispatch/request/session.rb:216:in `load!'
actionpack (5.1.7) lib/action_dispatch/request/session.rb:208:in `load_for_read!'
actionpack (5.1.7) lib/action_dispatch/request/session.rb:126:in `to_hash'
actionpack (5.1.7) lib/action_dispatch/request/session.rb:202:in `each'
rack (2.0.8) lib/rack/session/abstract/id.rb:191:in `stringify_keys'
rack (2.0.8) lib/rack/session/abstract/id.rb:126:in `update'
rack (2.0.8) lib/rack/session/abstract/id.rb:299:in `prepare_session'
rack (2.0.8) lib/rack/session/abstract/id.rb:258:in `context'
rack (2.0.8) lib/rack/session/abstract/id.rb:253:in `call'
rack (2.0.8) lib/rack/urlmap.rb:68:in `block in call'
rack (2.0.8) lib/rack/urlmap.rb:53:in `each'
rack (2.0.8) lib/rack/urlmap.rb:53:in `call'
rack (2.0.8) lib/rack/builder.rb:153:in `call'
sidekiq (5.2.7) lib/sidekiq/web.rb:103:in `call'
sidekiq (5.2.7) lib/sidekiq/web.rb:108:in `call'
actionpack (5.1.7) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
actionpack (5.1.7) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.1.7) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (5.1.7) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.7) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.7) lib/action_dispatch/routing/route_set.rb:844:in `call'
rack-pjax (1.1.0) lib/rack/pjax.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/cookies.rb:613:in `call'
remotipart (1.4.3) lib/remotipart/middleware.rb:32:in `call'
rack (2.0.8) lib/rack/etag.rb:25:in `call'
rack (2.0.8) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.8) lib/rack/head.rb:12:in `call'
rack (2.0.8) lib/rack/session/abstract/id.rb:259:in `context'
rack (2.0.8) lib/rack/session/abstract/id.rb:253:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/cookies.rb:613:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.7) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.7) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
bugsnag (6.12.1) lib/bugsnag/integrations/rack.rb:49:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.8) lib/rack/method_override.rb:22:in `call'
rack (2.0.8) lib/rack/runtime.rb:22:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
rack (2.0.8) lib/rack/sendfile.rb:111:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
rack (2.0.8) lib/rack/urlmap.rb:68:in `block in call'
rack (2.0.8) lib/rack/urlmap.rb:53:in `each'
rack (2.0.8) lib/rack/urlmap.rb:53:in `call'
puma (4.3.1) lib/puma/configuration.rb:228:in `call'
puma (4.3.1) lib/puma/server.rb:681:in `handle_request'
puma (4.3.1) lib/puma/server.rb:472:in `process_client'
puma (4.3.1) lib/puma/server.rb:328:in `block in run'
puma (4.3.1) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by chawarong** [comment]
We're also seeing this error. Not sure what else can possibly break within the app. but so far only viewing sidekiq is breaking.

```
Jan 01 14:50:46 fingi app/web.1: RuntimeError ():
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.12/lib/rack/session/abstract/id.rb:34:in `to_s'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/type/string.rb:35:in `cast_value'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/type/value.rb:98:in `type_cast'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/type/value.rb:34:in `type_cast_from_user'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/attribute.rb:110:in `type_cast'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/attribute.rb:42:in `original_value'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/attribute.rb:37:in `value'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/attribute.rb:50:in `changed_from?'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/attribute_methods/dirty.rb:143:in `_field_changed?'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/attribute_methods/dirty.rb:116:in `save_changed_attribute'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/attribute_methods/dirty.rb:99:in `write_attribute'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/attribute_methods.rb:50:in `__temp__3756373796f6e6f59646'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/attribute_assignment.rb:54:in `public_send'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/attribute_assignment.rb:35:in `each'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/core.rb:566:in `init_attributes'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/core.rb:281:in `initialize'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-session_store-1.0.0/lib/active_record/session_store/session.rb:66:in `initialize'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/inheritance.rb:61:in `new'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/inheritance.rb:61:in `new'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-session_store-1.0.0/lib/action_dispatch/session/legacy_support.rb:47:in `find_session'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-session_store-1.0.0/lib/action_dispatch/session/legacy_support.rb:40:in `get_session_model'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-session_store-1.0.0/lib/action_dispatch/session/active_record_store.rb:83:in `block in write_session'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-session_store-1.0.0/lib/active_record/session_store/extension/logger_silencer.rb:47:in `silence_logger'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-session_store-1.0.0/lib/action_dispatch/session/active_record_store.rb:82:in `write_session'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-session_store-1.0.0/lib/action_dispatch/session/legacy_support.rb:26:in `set_session'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.12/lib/rack/session/abstract/id.rb:369:in `commit_session'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.12/lib/rack/session/abstract/id.rb:253:in `context'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.12/lib/rack/session/abstract/id.rb:247:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/query_cache.rb:36:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/rack/logger.rb:38:in `call_app'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/rack/logger.rb:20:in `block in call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/tagged_logging.rb:26:in `tagged'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/tagged_logging.rb:68:in `tagged'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/rack/logger.rb:20:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/request_store-1.1.0/lib/request_store/middleware.rb:8:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.12/lib/rack/methodoverride.rb:22:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.12/lib/rack/runtime.rb:18:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/static.rb:120:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/heroku-deflater-0.6.3/lib/heroku-deflater/skip_binary.rb:19:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.12/lib/rack/deflater.rb:35:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/heroku-deflater-0.6.3/lib/heroku-deflater/serve_zipped_assets.rb:54:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/rack-1.6.12/lib/rack/sendfile.rb:113:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/ssl.rb:24:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/rack-timeout-0.2.4/lib/rack/timeout.rb:108:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/sentry-raven-0.13.3/lib/raven/integrations/rack.rb:54:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/engine.rb:518:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/application.rb:165:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/railtie.rb:194:in `public_send'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/railtie.rb:194:in `method_missing'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-5.6.0.349/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/puma-3.12.2/lib/puma/configuration.rb:227:in `call'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/puma-3.12.2/lib/puma/server.rb:674:in `handle_request'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/puma-3.12.2/lib/puma/server.rb:476:in `process_client'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/puma-3.12.2/lib/puma/server.rb:334:in `block in run'
Jan 01 14:50:46 fingi app/web.1:   vendor/bundle/ruby/2.3.0/gems/puma-3.12.2/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Jan 01 
```

**Comment by gingerlime** [comment]
https://github.com/redis-store/redis-store/issues/324

**Comment by weatherpixie** [comment]
Like others above we're also experiencing issues with Rack 2.0.8 when viewing sidekiq. We’re using sidekiq-pro 4.0.3 and rails 5.2.2.1 

```
Backtrace:
Show code hunks
/gems/rack-2.0.8/lib/rack/session/abstract/id.rb:31 in to_s
/gems/redis-store-1.4.1/lib/redis/store/serialization.rb:56 in encode
/gems/redis-store-1.4.1/lib/redis/store/serialization.rb:5 in block in set
/gems/redis-store-1.4.1/lib/redis/store/serialization.rb:39 in _marshal
/gems/redis-store-1.4.1/lib/redis/store/serialization.rb:5 in set
/gems/redis-store-1.4.1/lib/redis/store/namespace.rb:7 in block in set
/gems/redis-store-1.4.1/lib/redis/store/namespace.rb:88 in namespace
/gems/redis-store-1.4.1/lib/redis/store/namespace.rb:7 in set
/gems/redis-rack-2.0.4/lib/rack/session/redis.rb:61 in block (2 levels) in set_session
/gems/redis-rack-2.0.4/lib/rack/session/redis.rb:94 in with
/gems/redis-rack-2.0.4/lib/rack/session/redis.rb:61 in block in set_session
/gems/redis-rack-2.0.4/lib/rack/session/redis.rb:79 in with_lock
/gems/redis-rack-2.0.4/lib/rack/session/redis.rb:60 in set_session
/gems/rack-2.0.8/lib/rack/session/abstract/id.rb:498 in write_session
/gems/rack-2.0.8/lib/rack/session/abstract/id.rb:381 in commit_session
/gems/rack-2.0.8/lib/rack/session/abstract/id.rb:261 in context
/gems/rack-2.0.8/lib/rack/session/abstract/id.rb:253 in call
/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99 in call
/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/cookies.rb:670 in call
/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99 in call
/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/callbacks.rb:28 in block in call
/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:98 in run_callbacks
/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/callbacks.rb:26 in call
/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99 in call
/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb:32 in call!
/gems/airbrake-9.4.3/lib/airbrake/rack/middleware.rb:21 in call
/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99 in call
/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:61 in call
/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99 in call
/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/show_exceptions.rb:33 in call
/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99 in call
/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15 in call_app
/gems/railties-5.2.2.1/lib/rails/rack/logger.rb:26 in block in call
/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:71 in block in tagged
/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:28 in tagged
/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:71 in tagged
/gems/railties-5.2.2.1/lib/rails/rack/logger.rb:26 in call
/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99 in call
/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/remote_ip.rb:81 in call
/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99 in call
/gems/request_store-1.4.1/lib/request_store/middleware.rb:19 in call
/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99 in call
/gems/rack-timeout-0.5.1/lib/rack/timeout/core.rb:123 in block in call
/gems/rack-timeout-0.5.1/lib/rack/timeout/support/timeout.rb:19 in timeout
/gems/rack-timeout-0.5.1/lib/rack/timeout/core.rb:122 in call
/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99 in call
/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/request_id.rb:27 in call
/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99 in call
/gems/rack-2.0.8/lib/rack/method_override.rb:22 in call
/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99 in call
/gems/rack-2.0.8/lib/rack/runtime.rb:22 in call
/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99 in call
/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/executor.rb:14 in call
/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99 in call
/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/static.rb:127 in call
/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99 in call
/gems/rack-2.0.8/lib/rack/sendfile.rb:111 in call
/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99 in call
config/initializers/filter_external_domain_requests.rb:13 in call

11:

12:
      def call(env)
13:
        return @app.call(env) if Settings.app.external_guid_setter_base_urls.blank?
14:

15:
/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99 in call
/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/ssl.rb:74 in call
/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99 in call
/gems/rack-cors-1.1.0/lib/rack/cors.rb:100 in call
/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99 in call
/gems/railties-5.2.2.1/lib/rails/engine.rb:524 in call
/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99 in call
/gems/puma-4.3.1/lib/puma/configuration.rb:228 in call
/gems/puma-4.3.1/lib/puma/server.rb:681 in handle_request
/gems/puma-4.3.1/lib/puma/server.rb:472 in process_client
/gems/puma-4.3.1/lib/puma/server.rb:328 in block in run
/gems/puma-4.3.1/lib/puma/thread_pool.rb:134 in block in spawn_thread
```

**Comment by TrishaPatel** [comment]
I am getting same error. 
undefined method `match' for #<Rack::Session::SessionId:0x0000561cb21aeb48>

How can i resolved it?

**Comment by joelmoss** [comment]
I'm coming across the same problem when `to_s` is called on the session ID in Rails...

```ruby
session.id.to_s
```

This happens for me, as I am saving the session ID in a DB table, and rails tries type casting to a string, as that is the what the DB column needs. So that makes sense. But of course, rack raise a `RuntimeError`, but with no explanation.

A workaround I found, is to use `session.id.public_id` instead of just `session.id`, which is an actual `String`.

**Comment by tenderlove** [comment]
The issue is that the session id can be used as a vector for timing attacks and can lead to session hijacking.  In order to work around the problem, we've split the session id in to two parts: a public id and a private id and made it a complex object.  The public id is ok for anyone to know, and the private id must be kept secret.  Casting this complex object to a string could have a couple issues (off the top of my head):

1. The private id could be leaked
2. If you're storing the id, which do you want? (Probably not the public id as you need to look the session up by the private id)
3. If we let `to_s` keep the default implementation storage systems would store the output of `inspect`.  Rather than have corrupted data in your data store, an exception seemed better.

In any case casting the id to a string is likely an error and rather than just doing the default thing of calling inspect, I thought it would be better that an exception was raised because we don't actually know which id you want. 

I should have made the error better and I apologize for that.  You should use `public_id` or `private_id` depending on your use case.

**Comment by jdurand** [comment]
Thanks for the explanation @tenderlove. Since this is a breaking change shouldn't this be part of 2.1.x?

**Comment by tenderlove** [comment]
@jdurand Yes, it will also be a part of 2.1.x.  But I don't think it would be a good idea to leave the other series unpatched as this is a security fix.  We made it as backwards compatible as we could while keeping applications secure.

**Comment by dylanbromby** [comment]
I understand the tension created between the importance of the security fix and making the library backwards compatible, but there just seems to be a little irresponsibility including a significant, breaking change in a maintenance release. It might've caused less trouble to issue a notice, but put the breaking change in a minor point release.

**Comment by eileencodes** [comment]
@dylanbromby no one on the Rack or Rails team was irresponsible here. We weighed MANY options and tried other ways of fixing it and this is where we ended up. We aim not to break applications but sometimes it's not just possible.

Let's keep this issue focused on solutions for the problem at hand, not rehashing whether we did the release wrong.

**Comment by jdurand** [comment]
This will be fixed when https://github.com/redis-store/redis-rack/pull/50 is merged, so for now just `gem 'rack', '!= 2.0.8'`

**Comment by le0pard** [comment]
We need https://github.com/redis-store/redis-rack/pull/50 and https://github.com/redis-store/redis-actionpack/pull/28 changes, so redis session will work with new rack 2.0.8 changes.

**Comment by dentarg** [comment]
Are the issues reported here fixed by https://github.com/rack/rack/pull/1469? (see also https://github.com/rack/rack/issues/1433#issuecomment-573251375)

**Comment by jeremyevans** [comment]
Yes, this issue was fixed by #1469, and has been backported already.

**Comment by gingerlime** [comment]
Thanks @jeremyevans I tried to update rack to 2.1.1 but am still seeing an error accessing the sidekiq web console (using sidekiq 6.0.4 and rails 6.02.1, as well as upgrading redis-rack to 2.1.0 and redis-actionpack to 5.2.0)

![Screenshot 2020-01-14 at 12 36 15](https://user-images.githubusercontent.com/524274/72317096-c84cee00-36ca-11ea-87a4-24713183d006.png)

This is with redis-rack 2.0.6, however upgrading to

**Comment by PikachuEXE** [comment]
Actually `rack` `2.1.0 - 2.1.1` got another issue so I stay at `2.0.8`
And it seems (coz I haven't tested it) the issue is already fixed by https://github.com/rack/rack/commit/f690bb71425aa31d7b9b3113829af773950d8ab5
Which is not released yet

**Comment by gingerlime** [comment]
Thanks @PikachuEXE ! I can also confirm that 2.0.8 works.

**Comment by kannans5** [comment]
I am also experiencing the same issue with sidekiq web console. I am seeing the rack gem only in my Gemfile.lock, how do I pin this version 2.0.8 in my Gemfile.lock?

**Comment by JF-Lalonde** [comment]
@kannans5 You'll want to delete your Gemfile.lock and specify the rack version in your Gemfile.
Putting something like this in your Gemfile will "pin" the version to 2.0.8
```
gem "rack", "2.0.8"
```
Then just run `bundle install` to generate an updated Gemfile.lock and you should be good to go!

**Comment by yourivdlans** [comment]
I'd advise anyone against removing their `Gemfile.lock` as running `bundle install` afterwards could update gems you don't want updated.

Rather lock the gem like @JF-Lalonde is suggesting and run `bundle update rack`.

**Comment by JF-Lalonde** [comment]
@yourivdlans Thanks for the clarification; I was blindly making the assumption that the other gems in the Gemfile had version constraints to prevent unwanted updates. I'm sure that's not the case for many people.

**Comment by hiroshi** [comment]
Hi, I just want to share our situation.
Our production rails app needs `SameSite=None` cookie, but it require rack 2.1.0 or above;
https://github.com/rack/rack/blob/master/CHANGELOG.md#210---2020-01-10
Also it is using sidekiq, so I want to avoid from 2.0.8 to 2.1.1.

Chrome 80 regards SameSite=Lax as default;
https://www.chromium.org/updates/same-site
and will be released in Feb 4;
https://www.chromestatus.com/features/schedule

I'm not sure the next release, maybe 2.1.2, including the fix https://github.com/rack/rack/commit/f690bb71425aa31d7b9b3113829af773950d8ab5
is going to be released before Feb 4.

So I decided to use the commit instead of latest released version.

**Comment by dpsk** [comment]
Just a reminder to everyone stuck with the issue that you also need to clear your session before testing.
Can use incognito window to verify fix is working too. `redis-rack` 2.1.2 and `rack` 2.2.2 worked for me.

**Comment by jmugatu** [comment]
To follow-up on @dpsk's comment, you also need to upgrade `redis-actionpack` to 5.2.0.

**Comment by silva96** [comment]
> one stuck with the issue that you also need to clear your session before testing.
> Can use incognito window to verify fix is working too. `redis-rack` 2.1.2 and `rack` 2.2.2 worked for me.

Life savior

**Comment by feliperaul** [comment]
Could anyone explain why I need to clear my session before testing? I can't understand why I still have the exception even after **logging out and back in** (shouldn't this destroy the previous session?) but not when using icognito mode.

I'm having the same issue with Sidekiq as everyone else, but I'm afraid our users might be impacted in a public page somewhere.

**Comment by aesyondu** [comment]
> We are also experiencing issues with version 1.6.12, which fixes the same CVE:
> 
> ```
> # /usr/local/bundle/gems/rack-1.6.12/lib/rack/session/abstract/id.rb:34:in `to_s'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rack-1.6.12/lib/rack/utils.rb:36:in `escape'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rack-1.6.12/lib/rack/utils.rb:329:in `block in set_cookie_header!'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rack-1.6.12/lib/rack/utils.rb:329:in `map'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rack-1.6.12/lib/rack/utils.rb:329:in `set_cookie_header!'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/cookies.rb:352:in `block in write'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/cookies.rb:352:in `each'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/cookies.rb:352:in `write'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/cookies.rb:564:in `call'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/query_cache.rb:36:in `call'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/airbrake-4.3.1/lib/airbrake/rails/middleware.rb:13:in `call'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/railties-4.2.11.1/lib/rails/rack/logger.rb:38:in `call_app'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rails_semantic_logger-4.1.3/lib/rails_semantic_logger/extensions/rails/rack/logger.rb:21:in `call'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rack-1.6.12/lib/rack/methodoverride.rb:22:in `call'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rack-1.6.12/lib/rack/runtime.rb:18:in `call'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rack-1.6.12/lib/rack/lock.rb:17:in `call'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/static.rb:120:in `call'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rack-1.6.12/lib/rack/sendfile.rb:113:in `call'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/airbrake-4.3.1/lib/airbrake/user_informer.rb:16:in `_call'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/airbrake-4.3.1/lib/airbrake/user_informer.rb:12:in `call'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/railties-4.2.11.1/lib/rails/engine.rb:518:in `call'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/railties-4.2.11.1/lib/rails/application.rb:165:in `call'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/rack-test-0.6.3/lib/rack/test.rb:124:in `request'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/testing/integration.rb:297:in `process'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/testing/integration.rb:32:in `get'
> build	19-Dec-2019 15:03:35	      # /usr/local/bundle/gems/actionpack-4.2.11.1/lib/action_dispatch/testing/integration.rb:346:in `block (2 levels) in <module:Runner>'
> ```

Hi, what version did you rollback to that worked?
