### ISSUE TITLE
Version 2.2.x breaks Rails Actioncontroller:Live streaming

### ISSUE THREAD

**Issue by alor** [rack/rack#1619]
When you upgrade rack from 2.1.x to 2.2.x the streaming functionality in rails stops working.
A simple controller like this:

```ruby
class MyController < ActionController::Base
  include ActionController::Live

  def index

    response.headers["X-Accel-Buffering"] = "no"
    response.headers['Content-Type'] = 'text/event-stream'

    5.times do |i|
      logger.info "stream"

      response.stream.write "hello #{i}\n"
      sleep 1
    end
  rescue ActionController::Live::ClientDisconnected => e
    # ignore client disconnections
    nil
  ensure
    response.stream.close
  end
  
end
```
will not stream anymore and will send all the data at the end of the cicle.
After many attempts I've pinned down that the culprit is Rack 2.2.x.

with version 2.2.0 if you invoke that controller will raise an exception:

```
#<NoMethodError: undefined method `reject' for nil:NilClass>
ruby-2.6.5@mod/gems/rack-2.2.0/lib/rack/request.rb:623:in `reject_trusted_ip_addresses'
ruby-2.6.5@mod/gems/rack-2.2.0/lib/rack/request.rb:363:in `ip'
ruby-2.6.5@mod/gems/actionpack-5.1.2/lib/action_dispatch/http/request.rb:250:in `ip'
ruby-2.6.5@mod/gems/railties-5.1.2/lib/rails/rack/logger.rb:51:in `started_request_message'
ruby-2.6.5@mod/gems/railties-5.1.2/lib/rails/rack/logger.rb:35:in `block in call_app'
ruby-2.6.5/lib/ruby/2.6.0/logger.rb:465:in `add'
```

with version 2.2.1 no exception is raised but the streaming does not work. same on version 2.2.2

I've tested it with Rails 5.1.x and 6.0.2.1 (the latest). Same behaviour.

**Comment by jeremyevans** [comment]
Sorry for the delay in responding.  I think Rails was premature to close this issue.  We have not confirmed it is a bug in Rack (it may be, but we don't know yet).  It could be due to Rails relying on Rack implementation details that changed between Rack 2.1 and Rack 2.2.

Can you please do at least one of the following (preferably both):

1) Use git bisect to determine which commit in Rack made it start failing?

2) Remove the Rails specific parts of your example code and provide a self-contained reproducer that fails on Rack 2.2 and succeeds on Rack 2.1.

**Comment by ioquatix** [comment]
I am happy to investigate this too, but ideally need an isolated example as outlined above. Otherwise, can you make a rails app (in a github repo) which fails, with instructions on what to do to make it fail.

**Comment by rafaelfranca** [comment]
This is likely the commit that broke it. https://github.com/rack/rack/commit/290523f67cc43c5847b2be2d12964d1232061fe1

Looking the reported backtrace it is very clear that this is broken in rack not Rails. It is failing when calling `Rack::Request#ip` and Rails has no part to play in that method.

`Rack::Request#forwarded_for` is returning `nil` and that is what is failing https://github.com/rack/rack/blob/39d501a28c1fe51284addfe6dacffafb69d49849/lib/rack/request.rb#L361.

Before that commit the code correspondent to `forwarded_for` always returned an Array.

https://github.com/rack/rack/commit/290523f67cc43c5847b2be2d12964d1232061fe1#diff-345b5336fcb3ce47a50decd2176d79e8L291-L292.

**Comment by rafaelfranca** [comment]
A fix would change `forwarded_for` to return an array or change `reject_trusted_ip_addresses` to deal with `nil`.

**Comment by ioquatix** [comment]
Yeah, it's my fault, I'll fix it. Sorry everyone!

**Comment by ioquatix** [comment]
The issue @rafaelfranca mentions is fixed already in v2.2.2

So there is some other reason why live streaming is not working.

Not sure what it is yet, investigating.

**Comment by ioquatix** [comment]
It looks like `Rack::ETag` is buffering the live response.

**Comment by ioquatix** [comment]
This `config/application.rb` avoids the issue:

```
module Streamy
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 5.2

    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration can go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded after loading
    # the framework and any gems in your application.

    config.middleware.delete Rack::ETag
  end
end
```

**Comment by ioquatix** [comment]
```
koyoko% curl -i --no-buffer http://localhost:3000/streaming
HTTP/1.1 200 OK
Content-Type: text/event-stream
Cache-Control: no-cache
X-Request-Id: 2747eb62-e12a-4a64-a48d-7ba51df3b383
X-Runtime: 0.002133
Transfer-Encoding: chunked

hello world
hello world
hello world
hello world
hello world
```

https://github.com/rack/rack/commit/0371c69a0850e1b21448df96698e2926359f17fe

What should we do? Revert?

**Comment by ioquatix** [comment]
Here is the discussion: https://github.com/rack/rack/pull/1416

I've often thought `cache-control` needed a few extra flags:

- `static` - content which is quickly generated and/or easily reproduced without much effort.
- `dynamic` - content which has been generated dynamically and therefore is a good candidate for caching.
- `streaming` - content which is dynamically generated in an incremental fashion. Can be cached provided it isn't specified `no-cache` and cache operation doesn't impact streaming behaviour.

**Comment by ioquatix** [comment]
Rather than using `cache-control`, it looks like `pragma` would be an acceptable header as [defined by the RFC](https://tools.ietf.org/html/rfc7234#section-5.4)

**Comment by ioquatix** [comment]
Actually it looks like we can add custom tokens to cache-control: https://tools.ietf.org/html/rfc7234#section-5.2.3

**Comment by jefflasslett** [comment]
I'm out of my depth here, but humour me.
Yesterday I reported this issue to rails: https://github.com/rails/rails/issues/38842
Basically, my SSE would not work and I tracked it down to `Rack::ETag`.

The calculation of the `digest` in `Rack::ETag` replaced the original body of the response.
I observed that, in my SSE response, the body was a `Thread::SizedQueue`.  This is something that threads synchronise on.  `Rack::ETag` replaced it with an `Array`.

I think this is at the core of the issue, but I acknowledge that I am not "in my lane".  FWIW.

**Comment by jeremyevans** [comment]
`Thread::SizedQueue#each` is not defined, so a rack response where the body is a `Thread::SizedQueue` instance violates the rack spec, and any behavior in that case is undefined.  I doubt that is actually the case, there may be other Rails magic going on to make it look like the body is `Thread::SizedQueue` when it is actually something else (or the `each` method is coming from elsewhere).

In any case, the issue is that `Rack::ETag` was previously not generating the ETag if `Cache-Control` was set to `no-cache`, and Rails sets that for the SSE responses.  We started generating the ETag as a result of #1416.  We could revert the #1416 change and it would fix the issue, but then we are left with the previous behavior where the ETag is not generated for all `no-cache` responses.  Alternatively, Rails SSE support could set an ETag header on SSE responses.  `Rack::ETag` does not generate the ETag if there is already an ETag header, so that would also fix the issue.

**Comment by jefflasslett** [comment]
> `Thread::SizedQueue#each` is not defined, so a rack response where the body is a `Thread::SizedQueue` instance violates the rack spec,

Yep.  The body has to respond to `each`

> I doubt that is actually the case, there may be other Rails magic going on to make it look like the body is `Thread::SizedQueue`

I could have become confused.  The data in the response is complex.  But I did `pry` through it.  Also, I couldn't invent it.  Before yesterday, I hadn't even heard of `Thread::SizedQueue`.  :-)
Also, making the body only appear to be a `Thread::SizedQueue` seems a bit of a contortion.
So confusion on my part is a possibility, but it might be worth checking out.

>  `Rack::ETag` does not generate the ETag if there is already an ETag header, so that would also fix the issue.

That's what I went with.

**Comment by ioquatix** [comment]
@jefflasslett excellent work debugging the issue and finding a solution.

I think a better solution is needed. Maybe this is another point in favour of `body#call` style approach.

I think I will implement support for `cache-control: streaming` in falcon because I do need it to improve cache handling. However, I think there are multiple equally good solutions here, so happy to continue the discussion.

**Comment by jefflasslett** [comment]
Thanks @ioquatix .  FWIW, I was content to bypass `Rack::ETag` for my `text/event-stream` response as the whole idea of the `ETag` header and digest does not seem relevent to the event stream.

**Comment by ioquatix** [comment]
That makes sense. Can you show the code you used to bypass `ETag` in case someone else wants to use the same approach?

Then, maybe a 3rd option is to sniff the `content-type` and don't generate `ETag` for that particular one... but that also seems a bit unreliable to me.

**Comment by jefflasslett** [comment]
Here's a piece of the relevant controller.   You can set either of both of `ETag` or `Last-Modified` and that will cause `Rack::Etag` to let the response through without modifying the body, due to the `!skip_cache?(headers)` condition inside `Rack::ETag#call`.

Anyway, the controller fragment ...

```
  class CreditDecisionsController < ApplicationController
    include ActionController::Live

    def subscribe
      connect_to_redis
      app_number = find_application_number
      @redis_channel = "#{current_user.login}:#{app_number}"
      
      headers['Content-Type'] = 'text/event-stream'

      # These seem to be needed here, or the etag middleware
      # will add the 'etag' header and replace the body of the response, which will
      # kill the response. This is due to the way the etag middleware calculates
      # the digest value for the header.
      headers['Last-Modified'] = '0'
      headers['ETag'] = '0'

      @sse = SSE.new(response.stream, event: 'credit_decision')

      # The rest deleted.  You get the picture.
```
Probably should set `ETag` and/or `Last-Modified` properly, but that works.

**Comment by ioquatix** [comment]
Thanks for the update!

To me:

```
      headers['Last-Modified'] = '0'
      headers['ETag'] = '0'
```

Looks like a hack. It's okay, but not great.

Because `0` is probably a valid etag.

**Comment by jefflasslett** [comment]
:-)  
That's fair.  I did say that they should be set "properly".   Just having either one present in the response will cause `Rack::ETag` to let the response through unchanged.

**Comment by alor** [comment]
what is the official status of this bug? will it be fixed soon or do we have to implement the workaround in our code as many are doing? thank you

**Comment by jeremyevans** [comment]
The behavior change to Rack::ETag was deliberate to fix #1416.  If another committer has strong feelings to revert the fix and leave #1416 broken, I'm fine with reverting.  Otherwise, I'll close this issue in about a week.

**Comment by alor** [comment]
IMHO the new behaviour is really broken, literally every example on how to stream response from rails will not work with rack 2.2.x and it's the default version installed when you start a project from scratch.
if you want to keep the new behaviour, we need to have a documentation explaining the breaking change and how to properly workaround it in the code.

**Comment by jeremyevans** [comment]
@tenderlove @rafaelfranca @eileencodes @matthewd You are all on the Rack and Rails core teams. What do you think we should do here?

**Comment by jeremyevans** [comment]
I've added pull request #1672 to revert to the historical behavior by default, but allow the 2.2.2 behavior via a keyword.  If other committers want to revert, I suggest we use the pull request, so that people that want the 2.2.2 behavior can get it.

**Comment by jeremyevans** [comment]
I'm going to close this and #1672 now.  If another committer wants to change the 2.2 behavior, they are welcome to reopen this and merge #1672.

**Comment by perryn** [comment]
Hello @jeremyevans ,

We just hit this problem in production and had to revert to 2.1.x.

I have read through this issue and I am unsure what the state of play is now?
It seems to me that there are currently no plans to make rails streaming work with 2.2.x, is that right?

Cheers
Perryn

**Comment by jeremyevans** [comment]
There are no current plans to revert the bug fix.  You can use one of the workarounds discussed above to make Rails streaming continue to work.  If one of the the rack committers who is also a rails committer wants to revert the bug fix, they are welcome to reopen this and do so (4 of the 6 rack committers are rails committers).  I even provided a pull request to make this easy (#1672).  However, since all have been mentioned and none have responded, it appears there is at least implicit agreement among committers that the bug fix should stay.

**Comment by alor** [comment]
I'm not sure the "tacit acceptance procedure" is ideal here. at least if they are also on the rails core, they should implement a fix in the rails code to insert the workaround on that part and they should declare how they want to procede. otherwise without anyone saying anything we will remain with a broken default installation of rails that is not able to stream responses.

**Comment by tenderlove** [comment]
> However, since all have been mentioned and none have responded, it appears there is at least implicit agreement among committers that the bug fix should stay.

@jeremyevans as you know, this is an open source project and not everyone can commit the same amount of time. Lack of response doesn't mean implicit agreement so lets adjust our expectations accordingly.

That said, I think the bug fix should probably stay (it is after all a bug fix).  Maybe we can put @jefflasslett's fix in Rails?

**Comment by jeremyevans** [comment]
@tenderlove fair enough.  I figured giving 4 committers 11 days to respond after mentioning them that I planned to close this resulted in a sufficiently low chance that there were objections, but that was apparently a miscalculation on my part. You can probably guess my feelings on leaving issue reports open indefinitely, so maybe we can come to an agreement on how long committers should wait for input from other committers before closing issues?  15 days, 30 days, etc.? What would you recommend?

**Comment by tenderlove** [comment]
1. I think 6 months is probably a good time frame, and we should set up a bot to do it (though we've had issues on the Rails tracker with anti bots: https://github.com/rails/rails/issues/37042#issuecomment-633939909 )
2. If you want someone to handle an issue like in this case, please just assign to them.  Then we know it's on their plate, and they can deal with it on their schedule.

**Comment by jeremyevans** [comment]
Personally, I consider 6 months way too long to wait for feedback, but if this process is only reserved for controversial issues, I don't have objections to that.

I have objections to using bots to close issues just because there is no recent response.  If an issue is a bug, it doesn't matter how long it is stale, it is still a bug, and we should do our best to fix all bugs.  Many of the bugs I have fixed since becoming a committer are bugs that have been present for many years.  It seems unlikely that someone is going to look through closed issues looking for ones that were closed for staleness.  It is much more likely someone will look at open bugs and try to triage/fix them.  In my opinion, automatically closing bug reports for staleness is the equivalent of ignoring the problem and hoping it goes away.

Picking a particular committer as an assignee for an issue where the committer is not already related to the code causing the issue is not something I would generally be comfortable doing.  In a case like this one, I'm not looking for a particular committer's action, I'm just soliciting feedback from all committers who did not already respond.  However, if you would prefer I assign issues to a specific committer in the future, I will do so.

**Comment by tenderlove** [comment]
> In a case like this one, I'm not looking for a particular committer's action, I'm just soliciting feedback from all committers who did not already respond.

My main concern is taking lack of response to mean implicit agreement. I don't particularly care about the means by which we prevent that.

**Comment by jeremyevans** [comment]
I apologize for implying there was implicit agreement.  I'm guessing if I had omitted `However, since all have been mentioned and none have responded, it appears there is at least implicit agreement among committers that the bug fix should stay.` from my earlier response, but otherwise took the same actions, we would not be having this conversation.

**Comment by tenderlove** [comment]
> I apologize for implying there was implicit agreement. I'm guessing if I had omitted `However, since all have been mentioned and none have responded, it appears there is at least implicit agreement among committers that the bug fix should stay.` from my earlier response, but otherwise took the same actions, we would not be having this conversation.

It's no problem. Your assessment of the situation is 100% correct, in that this is a bug, and it should remained fixed. I didn't comment on this issue because the bug (in Rails?) needs to be fixed, but I don't know how (or the right fix).  I'll try to be more communicative going forward, even if I don't know the right way to proceed.

**Comment by ioquatix** [comment]
I find bots that automatically close issues to be counter-productive. It's not only slightly offensive to the original person who spent time writing up the issue, it's also bad to close an issue just because it's old. The software quality would be noticeably worse IMHO. Everything else seems on point :)

**Comment by jarthod** [comment]
Hi, after spending some time trying to understand why streaming stopped working in my app I ended up finding this issue. I'm OK to use one of these workarounds of course but I also want to help as every Rails tutorials and documentation about streaming (which were already scarce) are now all non-functional.

I thought a bit about how to address that and I see that when enabling streaming with `render stream: true`, in addition to the `Cache-Control: no-cache` header (which has nothing to do with streaming), Rails also adds the `Transfer-Encoding: chunked` header (makes sense, this is about streaming). Source: https://github.com/rails/rails/blob/fe76a95b0d252a2d7c25e69498b720c96b243ea2/actionpack/lib/action_controller/metal/streaming.rb#L207

So wouldn't it be a good idea to skip the ETag middleware when the `Transfer-Encoding` header is set to `chunked` ? If you guys agree I can prepare a PR.

Thanks for your work!

**Comment by ioquatix** [comment]
> Transfer-Encoding header is set to chunked

That doesn't make sense to me - ETag can certainly apply to chunked responses.

**Comment by jarthod** [comment]
> That doesn't make sense to me - ETag can certainly apply to chunked responses.

I agree it can if generated manually from another source (like model data) instead of from the body itself. It does't make sense to generate an ETag from a chunked body as it means you'll have to buffer up all chunks first to generate the header and then send everything at once (so effectively breaking the chunking/streaming feature). Maybe I am missing something?

**Comment by ioquatix** [comment]
@jarthod yes you can generate an etag as a trailer.

**Comment by jarthod** [comment]
> @jarthod yes you can generate an etag as a trailer - your logic is pretty reasonable though.

I'm not sure what you mean by "trailer" here, if you're talking about generating an ETag after reading the whole body yes I know it's possible and that's what it's currently doing, but it doesn't mean this it is desirable when it's breaking streaming for endpoints that don't even require caching/ETag.

> As I suggested, I think we should introduce `cache-control: streaming` which prevents intermediate buffering OR have some other way to signal this.

I'm fine with that too if you prefer this option.

> Basically you are just considering the very specific case of `Rack::ETag` buffering the response, but there could be other middleware/proxies/caches/servers which cause the same problem and I don't know what the official solution is.

I don't see the link between the header we choose to use and the fact that other middlewares may break streaming too? `Transfer-Encoding: chunked` is AFAIK the "official" header indicating that HTTP streaming is being used (https://en.wikipedia.org/wiki/Chunked_transfer_encoding) so it still stands as the best candidate to me and it doesn't have anything specific to do with the ETag Middleware or even with Rails. `Cache-Control: streaming` would also have to be implemented by other middlewares as a new Rails-only standard so why would it be better in this regard?

**Comment by ioquatix** [comment]
> I'm not sure what you mean by "trailer" here

I literally mean HTTP trailers which follow the request. You can certainly stream out a chunked response and generate an etag for it and send it as a trailer. That's exactly what `async-http-cache` does.

The use of the word streaming on that wiki page is very confusing. If you look at the rationale on that page it actually has nothing to do with streaming and mostly about providing framing for persistent connections when the length of the body is not known in advance.

You can stream responses of HTTP/1.0 without chunked encoding, you just write data as you have it to the socket.

HTTP/2 is effectively always "chunked" as each data frame captures one chunk of the request/response body.

So, I don't see why `transfer-encoding: chunked` should disable ETag generation.

I'm actually find with disabling etag on `transfer-encoding: chunked` but this might actually break other things.

**Comment by ioquatix** [comment]
Actually, looking at https://github.com/alphagov/e-petitions/commit/46413a7127859e2d2d38a5e6f55ce3ec4504781f#diff-64ad1f6f49ed75b78218a21a5ba739e7189eddc10fcbe3767ebc34be011d0620R115

We see something similar to my proposed `cache-control: streaming`. I don't know if this belongs in the `cache-control` header but at least that's where I'd be using it in my use case.

**Comment by jarthod** [comment]
> I literally mean HTTP trailers which follow the request. You can certainly stream out a chunked response and generate an etag for it and send it as a trailer. That's exactly what async-http-cache does.

Ok I see, but `Rack::ETag` does not support this, if it does one day and is able to provide ETag without breaking streaming I guess it would ok in this case to keep generating the ETag (even if `Transfer-Encoding: chunked`) at the end. This is still compatible with my proposal.

> The use of the word streaming on that wiki page is very confusing. If you look at the rationale on that page it actually has nothing to do with streaming and mostly about providing framing for persistent connections when the length of the body is not known in advance (which is why it was introduced).
>
> You can stream responses of HTTP/1.0 without chunked encoding, you just write data as you have it to the socket
> HTTP/2 is effectively always "chunked" as each data frame captures one chunk of the request/response body.

I'm not sure why you are trying to prove that HTTP/1.1 streaming is not a thing? The first line of the rational you mention is exactly the purpose of streaming: "maintain an HTTP persistent connection for dynamically generated content"

> So, I don't see why transfer-encoding: chunked should disable ETag generation.

So I still don't see any valid argument against that, though I agree if it were Trailer and thus not breaking streaming it would be OK to keep generating it, but it's not the case currently.

> Actually, looking at alphagov/e-petitions@46413a7#diff-64ad1f6f49ed75b78218a21a5ba739e7189eddc10fcbe3767ebc34be011d0620R115
> 
> We see something similar to my proposed cache-control: streaming. I don't know if this belongs in the cache-control header but at least that's where I'd be using it in my use case.

Are you talking about the `X-Accel-Buffering` nginx header to disable buffering? If so yes it is similar in that it's a custom header to control another system, I agree. And if that's what the rack/rails team think we should address this bug I'm ok with it. Though I still think using the already existing header defining a streaming output would be much better:
- No changes to make in Rails, Sinatra, Hanami... and every other rack-compatible frameworks.
- Also works with any plain rack hijack endpoints or middleware returning this header to use streaming
- No custom value for Cache-Control (which even if theoretically allowed, may cause trouble in other systems)

Sounds silly to have to modify hundreds of open-source projects (and thousands of closed-source ones) to adapt to the new breaking change of `Rack::ETag`.

**Comment by ioquatix** [comment]
> I'm not sure why you are trying to prove that HTTP/1.1 streaming is not a thing?

I'm not sure where I said that. What I said is that `transfer-encoding: chunked` does not imply that the response body is "streaming".

There is a difference between streaming as in a long running bi-directional connection, and streaming as in dynamically generating an HTML page one chunk at a time. The latter still benefits from `etags`. The buffering mechanism of the `etag` middleware is questionable at best though.

`transfer-encoding` is a protocol level concern, to do with the framing of data. It's not even a valid header for HTTP/2. I also don't believe it's a good indicator of "this response body should not be buffered in any way". It definitely shouldn't be in the response headers from Rack. Falcon will complain if you do this.

I don't think any middleware should be buffering the response. This is simply a bad design. For example, if the response body is 10GiB of streaming data, it will cause major problems, whether it's chunked or not.

So, the problem is that `Rack::ETag` should not buffer the response. In fact, no middleware should assume a finite length body, unless... `body` is an instance of `Array` we can make some assumptions about it.

So the solutions are one or more of:

- Remove `Rack::ETag` as it's a bad design and encourages a bad buffering strategy.
- Change `Rack::ETag` to add `ETag` as a trailer (need to extend the semantic model of Rack a bit to handle trailers).
- Check whether the response body is already buffered (instance of Array of Strings) and only generate ETag in this case.
- Add a different mechanism for streaming responses (e.g. body has a fundamentally different interface than `#each`).

Even given all of the above, I'm actually still against buffering the response in any case. It's essentially an anti-pattern with clearly defined problems (buffering infinite response).

**Comment by jarthod** [comment]
I totally agree that no middleware should buffer, these would be some ideal solutions ;) but that's gonna take more time to fix the bug which is already present for all the code and tutorials written in the past 10 years using Rails streaming. We need a rather quick solution first if we want to respect the time of other developers, because while we discuss the number of people wasting hours trying to figure this out is increasing as they upgrade to rack 2.2 or start trying to use streaming.

> Remove Rack::ETag as it's a bad design and encourages a bad buffering strategy.

I tend to agree because although this implementation (in conjunction with `Rack::ConditionalGet`) does allow to return some shorter 304 bodies, the server still has to generate everything. Only some custom controller implementation of ETag can yield real performance benefits by not generating the body at all. Though in most standard cases (non chunked pages) I guess it can bring a little benefit especially on constrained bandwidth.

> Change Rack::ETag to add ETag as a trailer (need to extend the semantic model of Rack a bit to handle trailers).

Yeah I don't know the internals of rack well but that sounds more risky and complicated.

> Check whether the response body is already buffered (instance of Array of Strings) and only generate ETag in this case.

I haven't looked at the different type of objects returned by Rails here but if it's easy to distinguish that could be a good (and quick) solution indeed, as it wouldn't need to modify Rails and wouldn't change the ETag behavior for most people. I'll try to have a look at this.

**Comment by jarthod** [comment]
Ok I had a quick look at improving `Rack::ETag` to use trailers, I saw the `Rack::TrailerBody` which should help with that but before doing anything I checked the support because I never heard of it so was surprised, as I expected [no browser really supports trailers](https://stackoverflow.com/questions/13371367/do-any-browsers-support-trailers-sent-in-chunked-encoding-responses) (they don't crash but ignore them so sending `ETag` as Trailer is as good as not sending it).

I also had a look if we can distinguish buffered from streaming body but unfortunately all the Rack body wrapper do a good job [at hiding everything and only exposing `#each`](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/http/response.rb#L487) so without digging through the internal (`instance_variable_get`) I don't see any good way to do this.

So I'll let the rack and rails team decide if they really want to implement some new mechanism for this and in the meantime for me and everybody who just want to get streaming back I wrote a small patch for `Rack::ETag` implementing the solution I recommend (disabling for "chunked" encoding):

```ruby
# Monkey patch for Rack::ETag (ver 2.2+) to prevent breaking streaming responses (chunked)
# See https://github.com/rack/rack/issues/1619 for more details on the problem

module Rack
  class ETag
    def skip_caching?(headers)
      headers.key?(ETAG_STRING) || headers[TRANSFER_ENCODING] == "chunked" || headers.key?('Last-Modified')
    end
  end
end
```

**Comment by ioquatix** [comment]
Who is setting the transfer encoding header?

**Comment by jarthod** [comment]
> Who is setting the transfer encoding header?

It's [Rails when using `stream: true`](https://github.com/rails/rails/blob/fe76a95b0d252a2d7c25e69498b720c96b243ea2/actionpack/lib/action_controller/metal/streaming.rb#L207) (and it overrides whatever value the user put before if any, unlike `Cache-Control`).

**Comment by ioquatix** [comment]
It's super weird for rails to set that header. To put it in context, you could absolutely stream over a non-chunked encoding body (HTTP/1 does this just fine). It's basically just allows you to reuse the connection if it's persistent in HTTP/1 because it provides additional framing. This header is also invalid in HTTP/2 because it doesn't make sense.

`transfer-encoding: chunked` simply does not imply "don't buffer this response". As I said before, buffering any response completely is a mistake.

I'm going to take the position that rails setting the `transfer-encoding` header is a bug, and the only part of the stack responsible for setting this header would be the server itself when negotiating the connection with the client. Falcon will complain if you try to set this header because falcon needs to support HTTP/1.0, HTTP/1.1, HTTP/2 and soon HTTP/3.

**Comment by ioquatix** [comment]
What we need is probably something like `cache-control: streaming` or `cache-control: no-buffer`. Does such a thing exist? I know I made reference to an nginx specific `x-` header previously, but surely something is standardised?

**Comment by jarthod** [comment]
> It's super weird for rails to set that header. To put it in context, you could absolutely stream over a non-chunked encoding body (HTTP/1 does this just fine). It's basically just allows you to reuse the connection if it's persistent in HTTP/1 because it provides additional framing.

Well I guess you're talking about TCP streaming but in practice I don't think browsers will try to render the html before it received everything (maybe it's ok for audio and video files though). If everybody on the Internet is doing HTML streaming like this I'm guessing it's likely the right way.

> This header is also invalid in HTTP/2 because it doesn't make sense.

Probably but that doesn't seem to be an issues (of course web server will not break streaming for every application). So in my case using nginx I see the header is dropped and the content is probably streamed using HTTP/2 native protocol, it still works fine.

> I'm going to take the position that rails setting the transfer-encoding header is a bug, and the only part of the stack responsible for setting this header would be the server itself when negotiating the connection with the client. Falcon will complain if you try to set this header because falcon needs to support HTTP/1.0, HTTP/1.1, HTTP/2 and soon HTTP/3.
> What we need is probably something like cache-control: streaming or cache-control: no-buffer. Does such a thing exist? I know I made reference to an nginx specific x- header previously, but surely something is standardised?

I am not an export in this so I'm just reporting what I see and read and used. Here is some reference confirming what I'm saying: 
https://weblog.rubyonrails.org/2011/4/18/why-http-streaming/
https://gist.github.com/CMCDragonkai/6bfade6431e9ffb7fe88

I'm not gonna spend my days trying to prove you wrong so if the Rails and Rack team agrees with you please go ahead.

**Comment by themilkman** [comment]
`response.headers['Last-Modified'] = Time.now.httpdate`

Works for me, thanks for pointing it out @jarthod!

I also ran into this problem and wasted quite some time into it. It also took a while to find this issue...

**Comment by jarthod** [comment]
> I also ran into this problem and wasted quite some time into it. It also took a while to find this issue...

Yes me too ☹ that's why I was trying to get the team to address this before the collective number of hours wasted on this grows exponentially but it doesn't seem to be bothering them..

**Comment by ioquatix** [comment]
> Well I guess you're talking about TCP streaming but in practice I don't think browsers will try to render the html before it received everything

You absolutely can stream without `transfer-encoding: chunked` I've tested it extensively: https://utopia-falcon-heroku.herokuapp.com/beer/index - and browsers will render it.

```
curl -N -i https://utopia-falcon-heroku.herokuapp.com/beer/index
```

**Comment by jarthod** [comment]
Ok, It's good to know that we can, but it doesn't help fixing the bug impacting everybody here

**Comment by ioquatix** [comment]
I believe this should be fixed by https://github.com/rack/rack/pull/1748 - we could consider backporting this. @jeremyevans what do you think?

**Comment by jeremyevans** [comment]
SPEC changes are features, not bugs, I don't think that change should be backported.

**Comment by ioquatix** [comment]
It wasn't just the SPEC changes but the way the ETag middleware works etc.

**Comment by jeremyevans** [comment]
The ETag middleware changes are only allowed because of the change to SPEC.  With the Rack 2.2 SPEC, they were considered a bug.  I was only OK with the SPEC change because it was a major version change, I would have been against merging it without a major version change.

**Comment by ioquatix** [comment]
We have decided not to backport this, so the fix in Rack 2.x is either:

- Don't use `Rack::ETag` as it will buffer your response.
- Wait for Rack 3.x (by the end of the year I hope).
- Use the hack suggested above: `response.headers['Last-Modified'] = Time.now.httpdate`.

**Comment by wynksaiddestroy** [comment]
Can someone verify that this issue was fixed in Rack 3.x? I tried to spy a relevant entry in the changelog, but couldn't find any. Thanks in advance!

**Comment by ioquatix** [comment]
It should be.

**Comment by gobijan** [comment]
Not fixed for me using Rails 7.0.4 + Ruby 3.2.0. Had to disable etag middleware.

**Comment by jeremyevans** [comment]
> Not fixed for me using Rails 7.0.4 + Ruby 3.2.0. Had to disable etag middleware.

Considering that Rails 7.0.4 requires Rack 2, that's expected.  You'll need to wait until Rails supports Rack 3.

**Comment by gobijan** [comment]
My bad. Sorry!

**Comment by vassebas** [comment]
For me it wasn't `rack` version was `puma` version. I was using `rails 5.2.4`, `rack 2.2.4` and `puma 6.0.0`. There is an [issue](https://github.com/puma/puma/issues/3007) in Puma repo about this. My temporal solution was downgrade Puma to `5.6.5` version.

**Comment by jarthod** [comment]
> For me it wasn't `rack` version was `puma` version. I was using `rails 5.2.4`, `rack 2.2.4` and `puma 6.0.0`. There is an [issue](https://github.com/puma/puma/issues/3007) in Puma repo about this. My temporal solution was downgrade Puma to `5.6.5` version.

About this problem which I also ran into, for the record the fix has already been released in puma `6.0.1` I believe, or at least in `6.0.2` that I'm using it's working fine.

**Comment by dentarg** [comment]
Yes, the streaming issue (https://github.com/puma/puma/issues/3000) was addressed in [Puma 6.0.1](https://github.com/puma/puma/blob/v6.0.2/History.md#601--2022-12-20) along with other issues (https://github.com/puma/puma/issues/2999).

**Comment by kavi-codes** [comment]
A quick fix would be adding response.headers["Last-Modified"] = Time.now.httpdate to the controller according to [this](https://medium.com/@thilonel/how-to-use-rails-actioncontroller-live-sse-server-sent-events-d9a04a286f77) article. It stops buffering and streams the event.

**Comment by renny-ren** [comment]
I'm developing on a new Rails 7 project today and found the stream response is not work. I'm following this doc (https://api.rubyonrails.org/v7.0.4/classes/ActionController/Live/SSE.html) to study SSE. 

It took me hours to find out the issue is about rack... Fortunately I find the hack solution here, yes I checked my rack version is `2.2.6`, the solution should be written on the doc I guess, can't believe I'm using a broken default installation of rails that is not able to stream responses.

**Comment by RogerPodacter** [comment]
To confirm for future people trying to get `ActionController::Live` working: currently it is *not* possible in Rails 7.0.4 to use `ActionController::Live`, correct?

**Comment by ioquatix** [comment]
I guess the answer is, streaming never really worked correctly with Rack 2.x unless very specific conditions were met.

**Comment by jeremyevans** [comment]
That's a bit hyperbolic.  Streaming worked fine in Rack 2 if you were not buffering the body (but Rack::ETag buffered the body by default). In Rack 2, you can either remove Rack::ETag from the middleware stack, or set the `ETag` or `Last-Modified` response headers to work around the issue.

**Comment by ioquatix** [comment]
Well, given that Rails includes `Rack::ETag` by default, I'm fairly sure my statement is accurate, considering the use case `ActionController::Live` which out of the box on Rails does not work and is widely reported as not working without the extra steps you mention.

**Comment by RogerPodacter** [comment]
Oh wow! I added `config.middleware.delete Rack::ETag` to my `application.rb` and now it works! It should definitely work out of the box, but I'm also shocked the fix is this simple (and yet basically impossible to find). This should go in the docs!

**Comment by megatux** [comment]
> Oh wow! I added `config.middleware.delete Rack::ETag` to my `application.rb` and now it works! It should definitely work out of the box, but I'm also shocked the fix is this simple (and yet basically impossible to find). This should go in the docs!

totally removing the Etag middleware could bring some performance implications. You should do that only for specific controllers/paths

**Comment by jeremyevans** [comment]
> Well, given that Rails includes `Rack::ETag` by default, I'm fairly sure my statement is accurate, considering the use case `ActionController::Live` which out of the box on Rails does not work and is widely reported as not working without the extra steps you mention.

It depends on how your statement is interpreted.  I interpreted `streaming` in your statement to mean `streaming with Rack`, whereas it appears you intended it to mean `streaming with Rails`.

**Comment by triskweline** [comment]
> totally removing the Etag middleware could bring some performance implications. You should do that only for specific controllers/paths

Note that default Rails layout the `ETag` middleware produces random `ETags` that can never produce a cache hit. This is due to Rails including randomly masked CSRF tokens and CSP nonces in the `<head>` or individual forms.  You may still see some performance benefits when you render partials without a full layout and without forms, or when rendering JSON.

I agree that including `Rack::ETag` in the default middleware stack should be reconsidered, but that's a discussion for Rails.

Further reading:

- [Rails issue: ETag changes for every same request/response](https://github.com/rails/rails/issues/29889)
- [Rack::SteadyETag gem](https://github.com/makandra/rack-steady_etag)

**Comment by renny-ren** [comment]
the issue can be time-consuming for Rails users to diagnose but the workaround is simple, I'm not sure I should write here but for future people trying to get `ActionController::Live` working, I added the workaround in the docs (see PR above).

> Note that Rails includes `Rack::ETag` by default, which will buffer your response. As a result, streaming responses may not work properly with Rack `2.2.x`, and you may need to implement workarounds in your application.
  You can either set the `ETag` or `Last-Modified` response headers or remove `Rack::ETag` from the middleware stack to address this issue.
  
Here's an example of how you can set the `Last-Modified` header if your Rack version is `2.2.x`:

```ruby
def stream
  response.headers["Content-Type"] = "text/event-stream"
  response.headers["Last-Modified"] = Time.now.httpdate # Add this line if your Rack version is 2.2.x
  ...
end
```

**Comment by ioquatix** [comment]
This should all be fixed in Rails 7.1 with Rack 3.

**Comment by jarthod** [comment]
For the record now that I have Rack 3.1.8, I just tried to remove this hack (in my case this monkeypatch to dynamically disable ETag only for chunked responses like before):
```ruby
module Rack
  class ETag
    def skip_caching?(headers)
      headers.key?(ETAG_STRING) || headers[TRANSFER_ENCODING] == "chunked" || headers.key?('Last-Modified')
    end
  end
end
```
But it now raises the following exception:
```
LocalJumpError (no block given (yield)):

actionpack (7.1.5) lib/action_controller/metal/streaming.rb:224:in `block in each'
actionview (7.1.5) lib/action_view/renderer/streaming_template_renderer.rb:24:in `rescue in each'
actionview (7.1.5) lib/action_view/renderer/streaming_template_renderer.rb:20:in `each'
actionpack (7.1.5) lib/action_controller/metal/streaming.rb:220:in `each'
actionpack (7.1.5) lib/action_dispatch/http/response.rb:109:in `to_ary'
actionpack (7.1.5) lib/action_dispatch/http/response.rb:511:in `to_ary'
rack (3.1.8) lib/rack/body_proxy.rb:51:in `method_missing'
rack (3.1.8) lib/rack/etag.rb:32:in `call'
rack (3.1.8) lib/rack/conditional_get.rb:31:in `call'
rack (3.1.8) lib/rack/head.rb:15:in `call'
```

When the ETag middleware tries to call `.to_ary`. There's nothing too custom on my end just a controller with `render stream: true` and the couple usual hacks requires to make streaming work in rails (calling `form_authenticity_token; flash` earlier) which have no impact on the render process.

@ioquatix maybe I'm missing something here but what change in Rack 3 was expected to fix this situation ?

**Comment by ioquatix** [comment]
@jarthod Can you please try Rails head and see if the issue is resolved?

**Comment by jarthod** [comment]
Ok I just tested locally with:
- Rails 7.2.2 : ❌ same exception
- Rails 8.0.0 : ❌ same exception
- Rails head on the 2024-11-15 (8aee12e) : ✅ seems to be working

So there is a recent fix for that which is not released yet I suppose?
But it also means that Rails 7.1, 7.2 and 8.0 (the most popular versions for the next couple years), with Rack 3, will all raise an exception when using Rails streaming. With no way for the users to understand why. This is a compatibility issue between rails streaming and the new Rack 3 interface I suppose? is there any way it could be backported?

**Comment by ioquatix** [comment]
Thanks for reporting back.

It was fixed in https://github.com/rails/rails/pull/51508 which was not merged in time for Rails 8.0 - it should probably be back-ported? cc @matthewd 

> This is a compatibility issue between rails streaming and the new Rack 3 interface I suppose?

Unfortunately, as per this issue, `ActionController::Live` streaming has been broken for a long time. The root cause of the issue was lack of specification around when it was appropriate to buffer a response, and when it was not. Rack 3 defined that, and updated `Rack::ETag` to follow this specification.

After defining the proper interface in Rack 3, Rails also needed to be updated to follow that specification. It has taken longer than I would like, but it looks like Rails 8.1 will ship with streaming that just works.

**Comment by KodyKendall** [comment]
The proposed workaround didn't work when I was running Rails 6.1 with Ruby 2.7 However, after upgrading my Rails app to 7.1, this workaround fixed the issue :). I was able to stay on Ruby 2.7, and delete the Etag in my application.rb file. 

> This `config/application.rb` avoids the issue:
> 
> ```
> module Streamy
>   class Application < Rails::Application
>     # Initialize configuration defaults for originally generated Rails version.
>     config.load_defaults 5.2
> 
>     # Settings in config/environments/* take precedence over those specified here.
>     # Application configuration can go into files in config/initializers
>     # -- all .rb files in that directory are automatically loaded after loading
>     # the framework and any gems in your application.
> 
>     config.middleware.delete Rack::ETag
>   end
> end
> ```
